### PR TITLE
Add MLJ usage to the README.md

### LINKED ISSUE #90: Code in Readme.md does not work.
I use `julia 1.6.1`
I installed LIBSVM.jl in Ubuntu as
`] add LIBSVM`

After that, I run the following source code in README.md.

```julia
using LIBSVM
using RDatasets

# Classification C-SVM
iris = dataset("datasets", "iris")
X = Matrix(iris[:, 1:4])
y = iris.Species

Xtrain = X[1:2:end, :]
Xtest  = X[2:2:end, :]
ytrain = y[1:2:end]
ytest  = y[2:2:end]

model = fit!(SVC(), Xtrain, ytrain)
ŷ = predict(model, Xtest)
```

But I get the following error.

```
ERROR: LoadError: MethodError: no method matching fit!(::SVC, ::Matrix{Float64}, ::CategoricalArrays.CategoricalVector{String, UInt8, String, CategoricalArrays.CategoricalValue{String, UInt8}, Union{}})
Closest candidates are:
  fit!(::Union{LIBSVM.AbstractSVC, LIBSVM.AbstractSVR}, ::AbstractMatrix{T} where T) at /home/****/.julia/packages/LIBSVM/5Z99T/src/ScikitLearnAPI.jl:68
  fit!(::Union{LIBSVM.AbstractSVC, LIBSVM.AbstractSVR}, ::AbstractMatrix{T} where T, ::Vector{T} where T) at /home/*****/.julia/packages/LIBSVM/5Z99T/src/ScikitLearnAPI.jl:68
  fit!(::LinearSVC, ::AbstractMatrix{T} where T, ::Vector{T} where T) at /home/******/.julia/packages/LIBSVM/5Z99T/src/ScikitLearnAPI.jl:100
Stacktrace:
 [1] top-level scope
   @ ~/***/***/***.jl:14
in expression starting at /home/*****/****/****/****.jl:14
```

### PR DESCRIPTION
**Pull request by ablaom**
I guess this also closes #90 .

@barucden @till-m

### CODE REVIEW

**Comment by barucden** [comment]
As far as I can tell, the whole example is written very clearly, and I have no objections in that regard. 

However, should this be in the LIBSVM repository? Would it make sense to add this example to the MLJ documentation, and add a section to our README dedicated to higher-level libraries that offer a better interface to LIBSVM?

**Comment by till-m** [comment]
I agree with @barucden. Anyone that want's to use LIBSVM.jl via MLJ will probably be drawn to MLJ documentation first and find the necessary information there.

@ablaom I hope you don't feel like @barucden and me reviewing the docstrings in JuliaAI/MLJLIBSVMInterface.jl#13 was somehow conditioned on you doing work for LIBSVM.jl in return. Speaking for myself at least, I can confidently say this is not the case and I am happy to help if I can.

> add a section to our README dedicated to higher-level libraries that offer a better interface to LIBSVM?

This seems like a good idea. What other higher-level libraries are there?

**Comment by ablaom** [comment]
Thanks for considering the PR. I don't have a strong opinion about whether it should go ahead. It isn't uncommon for small ML packages to offer a section on different interfaces, but it's extra maintenance. 

What if, for now at least, we drop the MLJ example completely but keep the directions for accessing the docstrings? Ie, stop at line 152?

**Comment by barucden** [comment]
I would vote for a section dedicated to different interfaces. I just think it's enough to provide a link/reference to these interfaces. I personally only know MLJ so far, but other interfaces may be added later.

However, that's just my opinion. Know that I am not more than an occasional contributor.

**Comment by barucden** [comment]
I would vote for a section dedicated to different interfaces. I just think it's enough to provide a link/reference to these interfaces. I personally only know MLJ so far, but other interfaces may be added later.

However, that's just my opinion. Know that I am not more than an occasional contributor.

**Comment by till-m** [comment]
@iblis17 If you have time, I think your input on this discussion would be much appreciated.

> I personally only know MLJ so far

[PredictMD.jl](https://github.com/bcbi/PredictMD.jl) seems to be another general-purpose framework for ML, but I am not sure it is still being maintained. More specialized packages include e.g. [GraphKernels.jl](https://github.com/simonschoelly/GraphKernels.jl) and [PosDefManifoldML.jl](https://github.com/Marco-Congedo/PosDefManifoldML.jl) though I am not sure it would be necessary to list specialized interfaces in any case -- I would think it unlikely someone looking to perform graph-based ML would end up on LIBSVM.jl instead of the actual GraphKernels.jl package GitHub.

**Comment by ablaom** [comment]
I've reduced the MLJ additions to the docstring references. That's just 10 lines. How's that?

**Review by till-m — APPROVED** [review]

**Comment by till-m** [comment]
@barucden @ablaom how do you want to proceed? There haven't been any complaints, so I would suggest going ahead with the merge sometime soon.

**Pull request merged**
