### PR TITLE
refine svmpredict

### PR DESCRIPTION
**Pull request by iblis17**
Ref:  https://github.com/JuliaML/LIBSVM.jl/pull/76#discussion_r650039472

~I imported the function `libsvm_predict_probability` and `libsvm_predict_values` for temporary and discussion needs.
They should be relocated later in #76.~ Rebased.

### CODE REVIEW

**Comment by barucden** [comment]
It would be great if we managed to make `svmpredict` more type-stable. Currently, the type of `pred` is uncertain, as well as `output` (before your commit). Perhaps we could define some auxiliary functions as they do [here](https://docs.julialang.org/en/v1/manual/performance-tips/#kernel-functions)? I believe it would result not only in more performant but also cleaner code.

**Comment by iblis17** [comment]
> It would be great if we managed to make `svmpredict` more type-stable.

I added `svmpredict_fill!`, it became slightly faster.

Before:
```julia
julia> A = rand(2, 2_000_000);

julia> @benchmark svmpredict($model, $A)
BenchmarkTools.Trial:
  memory estimate:  152.59 MiB
  allocs estimate:  15
  --------------
  minimum time:     1.185 s (0.10% GC)
  median time:      1.207 s (1.83% GC)
  mean time:        1.236 s (3.57% GC)
  maximum time:     1.305 s (7.68% GC)
  --------------
  samples:          5
  evals/sample:     1
```

After:
```julia
julia> @benchmark svmpredict($model, $A)
BenchmarkTools.Trial:
  memory estimate:  152.59 MiB
  allocs estimate:  16
  --------------
  minimum time:     1.062 s (0.11% GC)
  median time:      1.092 s (2.34% GC)
  mean time:        1.113 s (4.13% GC)
  maximum time:     1.195 s (8.72% GC)
  --------------
  samples:          5
  evals/sample:     1
```

**Comment by iblis17** [comment]
Given that there are some CI failures popped out randomly, I suspect that there are some GC safety issues

e.g.
https://github.com/JuliaML/LIBSVM.jl/pull/77/checks?check_run_id=2807830407

**Comment by iblis17** [comment]
@barucden good to go?

**Comment by barucden** [comment]
> @barucden good to go?

I am trying to replicate the issue caught by one of the tests. So far I did not succeed.

**Comment by iblis17** [comment]
I cannot reproduce that on my machine either.

I can add some `GC.@preserve` in other PR and let's see the random error pop out in future or not.

**Comment by barucden** [comment]
Alright :+1:

**Pull request merged**
